accelerate launch --main_process_port=13854 --gpu_ids 0,1,2,3,4,5,6,7 --num_processes 8 train_ficgen_fgcontrol_hrsc.py \
    --pretrained_model_name_or_path=/data/vepfs/public/xianbao01.hou/model/sd1-5 \
    --train_data_dir=/data/vepfs/public/xianbao01.hou/dataset/HRSC2016/HRSC2016/Train/AllImages \
    --img_patch_path=/data/vepfs/public/xianbao01.hou/dataset/HRSC2016/HRSC2016/Train/img_patch \
    --resolution=512 \
    --train_batch_size=1 \
    --gradient_accumulation_steps=1 \
    --allow_tf32 \
    --checkpointing_steps=15000 \
    --max_train_steps=75000 \
    --learning_rate=8e-5 \
    --max_grad_norm=1 \
    --lr_scheduler=constant --lr_warmup_steps=500 \
    --output_dir=/data/vepfs/public/xianbao01.hou/model/CC-Diff/FICGen/FICGen_hrsc_train_8e5_75000
