accelerate launch --main_process_port=13855 --gpu_ids 0,1,2,3,4,5,6,7 --num_processes 8 train_ficgen_dota.py \
    --pretrained_model_name_or_path=/data/vepfs/public/xianbao01.hou/model/sd1-5 \
    --train_data_dir=/data/vepfs/users/xianbao01.hou/CC-Diff/dataset/filter_train/images \
    --img_patch_path=/data/vepfs/users/xianbao01.hou/CC-Diff/dataset/filter_train/results/img_patch \
    --resolution=512 \
    --train_batch_size=1 \
    --gradient_accumulation_steps=40 \
    --allow_tf32 \
    --checkpointing_steps=300 \
    --num_train_epochs=100 \
    --learning_rate=1e-4 \
    --max_grad_norm=1 \
    --lr_scheduler=constant --lr_warmup_steps=0 \
    --output_dir=/data/vepfs/public/xianbao01.hou/model/CC-Diff/FICGen/FICGen_dota_train_e100_1e_4_bs320
